---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:

    - name: install httpd package
      yum:
        name: httpd
        state: installed
        notify: start apache

  handlers:       
    - name: start httpd service
      service:
        name: httpd
        state: started

