---
- name: Installing Nginx
  hosts: all
  become: true

  tasks:
    - name: Installing nginx package
      apt:
        name: nginx
        state: present
      notify: start nginx service
      
  handlers:
    - name: Start nginx service
      service:
        name: nginx
        state: started
