---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    yum:
      name: default-jdk
      state: installed
    when: ansible_os_family == "Debian"
  
  - name: Download tomcat packages
    get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz
        dest: /opt 

  - name: Extract the tomcat  tar.gz file
    unarchive:
        src: /opt/apache-tomcat-10.1.30.tar.gz
        dest: /opt/
        remote_src: yes
  
  - name: Ensure startup.sh has executable permissions
    file:
        path: /opt/apache-tomcat-10.1.30/bin/startup.sh 
        mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh 
    args:
        chdir: /opt/apache-tomcat-10.1.30/bin/

  
