---
- name: Uninstall httpd package
  hosts: all
  become: yes
  tasks:
    - name: Stop and disable httpd service
      service:
        name: httpd
        state: stopped
        enabled: no

    - name: Remove httpd package
      package:
        name: httpd
        state: absent

